#!/usr/bin/sh

#__________________
# Startup processes
#__________________

# Set the resolution and start picom
exec xrandr -s 3840x2160 &
picom &

# Set the cursor, volume and nvidia-led
xsetroot -cursor_name left_ptr &
#pactl set-sink-volume @DEFAULT_SINK@ 100% &
nvidia-settings -l &

# Enable clipboard history, numlock, hotkeys & notifications
gpaste-client start &
numlockx &
sxhkd &
dunst &

# Theming
$dir0/scripts/dynamic-wallpaper.sh &
#$dir0/customisation/colours/apply-colours.sh &

# Eww stuff
$ewwcmd daemon &
$ewwcmd open-many desktop backgroundbar bar desktop-mouse-actions &

# Run scripts
$dir0/scripts/volume.sh &


#____________
# BSPWM Setup
#____________

# Set the workspaces
bspc monitor -d 1 2 3 4

# Configure windows
bspc config border_width              0
bspc config -n focused border_width   0
bspc config focused_border_color      "#572525"
bspc config window_gap                50

# Configure window manager   
bspc config split_ratio               0.55
bspc config automatic_scheme          alternate
bspc config initial_polarity          second_child
bspc config borderless_monocle        true
bspc config gapless_monocle           false

# Geometry   
bspc config top_padding               40
bspc config bottom_padding            0
bspc config left_padding              0
bspc config right_padding             0
bspc config honor_size_hints          true
bspc config no_tiled_sizehints        false
bspc config presel_feedback_color     "#767b7e"

# Mouse options   
bspc config focus_follows_pointer     true
bspc config swallow_first_click       true
bspc config click_to_focus            any
bspc config pointer_action1           move
bspc config pointer_action2           resize_corner
bspc config pointer_action3           none



#____________
# BSPWM Rules
#____________

# Start BSPWM in floating mode
bspc rule -a '*' border=off state=floating
