import = ["<(envsubst < ~/.config/alacritty/alacritty.yml)"]
live_config_reload = true

[colors.dim]
black = "#272727"
blue = "#254057"
cyan = "#255457"
green = "#485725"
magenta = "#352557"
red = "#572525"
white = "#797979"
yellow = "#575725"

[colors.normal]
black = "#272727"
blue = "#254057"
cyan = "#255457"
green = "#485725"
magenta = "#352557"
red = "#572525"
white = "#797979"
yellow = "#575725"

[cursor]
blink_interval = 500
blink_timeout = 5
thickness = 1.0
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Shift"

[window]
decorations = "none"
dynamic_title = true
title = "Terminal"

[window.class]
general = "Terminal"
instance = "Terminal"

[window.dimensions]
columns = 90
lines = 45

[window.padding]
x = 30
y = 30
